# Generated by cvt <Width> <Height> <Rate>
xrandr --newmode "1280x960"  101.25  1280 1360 1488 1696  960 963 967 996 -hsync +vsync
xrandr --addmode eDP1 1280x960
xrandr --output eDP1 --mode 1280x960 --set "scaling mode" "Full"

# "xset r 66" for caps behaviour
setxkbmap us -v colemak && xset r 66

cd ~
picom &
feh --bg-max --randomize ~/.wallpaper/* &
exec dwm
